app/config/routes.rb
Rails.application.routes.draw do
  resources :support_requests
  devise_for :users

  root 'home#index'
  resources :support_requests

end

app/app/models/support_request.rb
class SupportRequest < ActiveRecord::Base
  belongs_to :user

  after_initialize :set_defaults

  scope :expired, -> { where(expired: true) }
  scope :not_expired, -> { where(expired: nil) }

  validates :user, :presence => true
  validates :provider, :presence => true
  validates :justification, :presence => true
  validates :ttl, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: Settings.default_request_ttl.to_i }
  validates :shared_key, :presence => true, length: {is: 32}

  def expired?()
	  if self.expired
	    true
	  else
	    (self.created_at + self.ttl.minutes) <= DateTime.now
	  end
  end

  private

  def set_defaults()
    unless persisted?
      self.ttl ||= Settings.default_request_ttl
      self.provider ||= Settings.default_request_tunnel_provider
      self.shared_key ||= Utils::generate_random_string(Settings.default_request_shared_key_size)
    end
  end
end

app/app/models/user.rb
class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable, :rememberable and :omniauthable
	devise :ldap_authenticatable, :rememberable, :trackable
	attr_accessible :username, :email, :password, :password_confirmation, :remember_me, :firstname, :lastname, :displayname
	has_many :support_requests

	before_save :get_ldap_lastname, :get_ldap_firstname, :get_ldap_displayname, :get_ldap_email

	validates :username, presence: true, uniqueness: true

	#hack for remember_token
	def rememberable_value
		Digest::SHA1.hexdigest("#{self.email}#{self.username}")[0,29]
	end

	private
	def get_ldap_lastname
		Rails::logger.info("### Getting the users last name")
		tempname = Devise::LDAP::Adapter.get_ldap_param(self.username,"sn").first
		puts "\tLDAP returned lastname of " + tempname
		self.lastname = tempname
	end

	def get_ldap_firstname
		Rails::logger.info("### Getting the users first name")
		tempname = Devise::LDAP::Adapter.get_ldap_param(self.username,"givenName").first
		puts "\tLDAP returned firstname of " + tempname
		self.firstname = tempname
	end

	def get_ldap_displayname
		Rails::logger.info("### Getting the users display name")
		begin
			tempname = Devise::LDAP::Adapter.get_ldap_param(self.username,"displayName").first
		rescue
			tempname = "#{self.firstname} #{self.lastname}"
		end
		self.displayname = tempname
	end

	def get_ldap_email
		Rails::logger.info("### Getting the users email address")
		begin
			tempmail = Devise::LDAP::Adapter.get_ldap_param(self.username,"proxyAddresses").first.split(":")[1]
		rescue
			tempmail = Devise::LDAP::Adapter.get_ldap_param(self.username,"mail").first
		end
		self.email = tempmail
	end
end

app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	rescue_from DeviseLdapAuthenticatable::LdapException do |exception|
		render :text => exception, :status => 500
	end
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception

	before_action :set_limit, only:[:index]
	before_action :set_offset, only:[:index]

	private
	def set_limit
		@limit = params.has_key?(:limit) ? params[:limit].to_i : -1
	end

	def set_offset
		@skip = params.has_key?(:skip) ? params[:skip].to_i : 0
	end
end

app/app/controllers/home_controller.rb
class HomeController < ApplicationController
  # GET /home
  def index
  end
end

app/app/controllers/login_required_controller.rb
class LoginRequiredController < ApplicationController
	  before_action :authenticate_user!
end

app/app/controllers/support_requests_controller.rb
class SupportRequestsController < LoginRequiredController
  before_action :set_support_request, only: [:show, :edit, :update, :destroy]

  # GET /support_requests
  # GET /support_requests.json
  def index
    @support_requests = current_user.support_requests.order(id: :desc)
    @support_requests = @support_requests.offset(@skip) unless @skip.nil? 
    @support_requests = @support_requests.first(@limit) unless @limit.nil? 
  end

  # GET /support_requests/1
  # GET /support_requests/1.json
  def show
  end

  # GET /support_requests/new
  def new
    @support_request = SupportRequest.new
  end

  # GET /support_requests/1/edit
  def edit
  end

  # POST /support_requests
  # POST /support_requests.json
  def create
    @support_request = SupportRequest.new(support_request_params)
    @support_request.user = current_user

    respond_to do |format|
      if @support_request.save
        format.html { redirect_to support_requests_url, notice: 'Support request was successfully created.' }
        format.json { render :show, status: :created, location: @support_request }
      else
        format.html { render :new }
        format.json { render json: @support_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /support_requests/1
  # PATCH/PUT /support_requests/1.json
  def update
    respond_to do |format|
      if @support_request.update(support_request_params)
        format.html { redirect_to support_requests_url, notice: 'Support request was successfully updated.' }
        format.json { render :show, status: :ok, location: @support_request }
      else
        format.html { render :edit }
        format.json { render json: @support_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /support_requests/1
  # DELETE /support_requests/1.json
  def destroy
    @support_request.destroy
    respond_to do |format|
      format.html { redirect_to support_requests_url, notice: 'Support request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_support_request
      @support_request = current_user.support_requests.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def support_request_params
      params.require(:support_request).permit(:justification, :ttl)
    end
end

app/app/helpers/application_helper.rb
module ApplicationHelper

	def error_tag(model, attribute)
		if model.errors.has_key? attribute
			content_tag(:div, model.errors[attribute].first, :class => 'error_message')
		else
			content_tag(:div, "", :class => 'error_message')
		end
	end

	def create_nav_link(path, text, controller, glyph)
		params[:controller] == controller ? c = "active" : c = ""
		content_tag :li, class: "#{c}" do
			link_to path do
				content_tag(:span, "", class: "glyphicon #{glyph}") +
					"    #{text}"
			end
		end 
	end

end

app/app/helpers/home_helper.rb
module HomeHelper
end

app/app/helpers/support_requests_helper.rb
module SupportRequestsHelper
end

app/app/views/home/index.html.erb
<div class="row">
	<div class="col-md-4"></div>
	<div class="col-md-4">
		<h2>Eu preciso de ajuda</h2>
		<%= form_tag("/support_requests/new", method: :get) do %>
			<%= submit_tag("Novo pedido de suporte",class: "btn btn-primary") %>
	<% end %>


		<h2>Eu quero ajudar</h2>
		<%= form_tag("/support_requests", method: :get ) do %>
			<div class="form-group">
			<%= label_tag(:shared_key, "Chave informada pelo cliente:") %>
			<%= text_field_tag(:shared_key, "",class: "form-control") %>
			<%= hidden_field_tag(:support, 1, class: "form-control") %>
		</div>
		<%= submit_tag("OK",class: "btn btn-primary") %>
	<% end %>
	</div>
	<div class="col-md-4"></div>
</div>

app/app/views/layouts/_guest_navbar.html.erb
<nav class="navbar navbar-inverse">
        <div class="container-fluid">
                <div class="navbar-header">
			<%= link_to "RS2", root_path, class: "navbar-brand" %>
                </div>
                <ul class="nav navbar-nav navbar-right">
			<li><%= link_to t("application.nav_bar.login"), new_user_session_path, :class => 'navbar-link' %> </li>
                </ul>
        </div>
</nav>

app/app/views/layouts/_user_navbar.html.erb
<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<div class="navbar-header">
			<%= link_to "RS2", root_path, class: "navbar-brand" %>
		</div>
		<ul class="nav navbar-nav">
			<%= create_nav_link(root_path, "Home", "home", "glyphicon-home") %>
			<%= create_nav_link(support_requests_path, t("application.nav_bar.requests_button"), "support_requests", "glyphicon-list-alt") %>
		</ul>
		<ul class="nav navbar-nav navbar-right">
			<li>
			<%= link_to destroy_user_session_path, method: :delete, :class => 'navbar-link' do%>
				<%="#{t("application.nav_bar.logged_as")}: #{current_user.firstname}"%>
				<span class="glyphicon glyphicon-off"></span>
			<% end %>
			</li>
		</ul>
	</div>
</nav>

app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>App</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<header>
			<% if user_signed_in? %>
				<%= render 'layouts/user_navbar'%>
			<% else %>
				<%= render 'layouts/guest_navbar'%>
			<% end %>
		</header>
		<div id="content" class="container">
			<div class="row">
				<div class="col-md-4"></div>
				<div class="col-md-4">
					<% if notice %>
						<p class="alert alert-success">
							<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
							<%= notice %>
						</p>
					<% end %>
					<% if alert %>
						<p class="alert alert-danger">
							<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
							<%= alert %>
						</p>
					<% end %>
				</div>
				<div class="col-md-4"></div>
			</div>
			<%= yield %>
		</div>
	</body>
</html>

app/app/views/support_requests/_form.html.erb
<%= form_for(@support_request) do |f| %>
	<% if @support_request.errors.any? %>
		<div id="error_explanation" class="alert alert-danger">
			<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
			<span class="sr-only">Error</span>
			<strong><%= pluralize(@support_request.errors.count, t('.error_banner_header.one'), t('.error_banner_header.other')) %>:</strong>
			<ul>
				<% @support_request.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class="form-group">
		<div class="field">
			<%= f.label :justification %>:<br>
			<%= f.text_area :justification, class: "form-control" %>
		</div>
	</div>
	<div class="actions">
		<%= f.submit t("defaults.create").capitalize,class: "btn btn-primary" %>
	</div>
<% end %>

app/app/views/support_requests/edit.html.erb
<h1>Editing Support Request</h1>

<%= render 'form' %>

<%= link_to 'Show', @support_request %> |
<%= link_to 'Back', support_requests_path %>

app/app/views/support_requests/index.html.erb
<h1><%= t '.title' %></h1>

<table class="table">
	<thead>
		<tr>
			<th><%= t '.th.id' %></th>
			<th><%= t '.th.shared_key' %></th>
			<th><%= t '.th.ttl' %></th>
			<th><%= t '.th.expired' %> </th>
			<th><%= t '.th.tunnel_availble' %></th>
			<th colspan="1"></th>
		</tr>
	</thead>

	<tbody>
	<% @support_requests.each do |support_request| %>
		<tr>
			<td><%= support_request.id %></td>
			<td><%= support_request.shared_key %></td>
			<td><%= support_request.ttl %></td>
			<td><%= support_request.expired? ? t('defaults.yes') : t('defaults.no') %></td>
			<td><%= support_request.tunnel_created_at.nil? || support_request.expired? ? t('defaults.no') : t('defaults.yes') %></td>
			<td>
				<%= link_to support_request do%>
					<% content_tag(:span, "", class: "glyphicon glyphicon-search") %>
				<%end%>
			</td>
		</tr>
	<% end %>
	</tbody>
</table>
<br>
<%= link_to t(".new_request_link"), new_support_request_path %>

app/app/views/support_requests/new.html.erb
<h2><%= t '.title' %></h2>

<%= render 'form' %>
<br>
<%= link_to t(".request_list_link"), support_requests_path %>

app/app/views/support_requests/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
	<div class="panel-heading"><%= "##{SupportRequest.model_name.human.capitalize} - #{@support_request.id}" %></div>
	<div class="panel-body">
		<p>
		<strong><%= SupportRequest.human_attribute_name(:justification).capitalize %>:</strong>
		<%= @support_request.justification %>
		</p>

		<p>
		<strong><%= SupportRequest.human_attribute_name(:shared_key).capitalize %>:</strong>
		<%= @support_request.shared_key %>
		</p>

		<p>
		<strong><%= SupportRequest.human_attribute_name(:provider).capitalize %>:</strong>
		<%= @support_request.provider %>
		</p>

		<p>
		<strong><%= SupportRequest.human_attribute_name(:created_at).capitalize %>:</strong>
		<%= @support_request.created_at %>
		</p>

		<p>
		<strong><%= SupportRequest.human_attribute_name(:tunnel_created_at).capitalize %>:</strong>
		<%= @support_request.tunnel_created_at.present? ? @support_request.tunnel_created_at.present : '--' %>
		</p>

		<p>
		<strong><%= SupportRequest.human_attribute_name(:ttl).capitalize %>:</strong>
		<%= @support_request.ttl %>
		</p>

		<p>
		<strong><%= SupportRequest.human_attribute_name(:expired).capitalize %>:</strong>
		<%= @support_request.expired? ? t("defaults.yes") : t("defaults.no")%>
		</p>

	</div>
</div>
<%= link_to 'Request list', support_requests_path %>